export const DATASET_PROCESS_REQUEST = "DATASET_PROCESS_REQUEST";
export const DATASET_PROCESS_SUCCESS = "DATASET_PROCESS_SUCCESS";
export const DATASET_PROCESS_FAIL = "DATASET_PROCESS_FAIL";

export const DATASET_FILE_REQUEST = "DATASET_FILE_REQUEST";
export const DATASET_FILE_SUCCESS = "DATASET_FILE_SUCCESS";
export const DATASET_FILE_FAIL = "DATASET_FILE_FAIL";