export const RESEARCH_SAVE_REQUEST = "RESEARCH_SAVE_REQUEST";
export const RESEARCH_SAVE_SUCCESS = "RESEARCH_SAVE_SUCCESS";
export const RESEARCH_SAVE_FAIL = "RESEARCH_SAVE_FAIL";

export const RESEARCH_GET_REQUEST = "RESEARCH_GET_REQUEST";
export const RESEARCH_GET_SUCCESS = "RESEARCH_GET_SUCCESS";
export const RESEARCH_GET_FAIL = "RESEARCH_GET_FAIL"

export const RESEARCHES_GET_REQUEST = "RESEARCHES_GET_REQUEST";
export const RESEARCHES_GET_SUCCESS = "RESEARCHES_GET_SUCCESS";
export const RESEARCHES_GET_FAIL = "RESEARCHES_GET_FAIL";

export const STUDY_SAVE_REQUEST = "STUDY_SAVE_REQUEST";
export const STUDY_SAVE_SUCCESS = "STUDY_SAVE_SUCCESS";
export const STUDY_SAVE_FAIL = "STUDY_SAVE_FAIL";

export const STUDY_GET_REQUEST = "STUDY_GET_REQUEST";
export const STUDY_GET_SUCCESS = "STUDY_GET_SUCCESS";
export const STUDY_GET_FAIL = "STUDY_GET_FAIL";