export const RESEARCH_SAVE_REQUEST = "RESEARCH_SAVE_REQUEST";
export const RESEARCH_SAVE_SUCCESS = "RESEARCH_SAVE_SUCCESS";
export const RESEARCH_SAVE_FAIL = "RESEARCH_SAVE_FAIL";

export const RESEARCH_GET_REQUEST = "RESEARCH_GET_REQUEST";
export const RESEARCH_GET_SUCCESS = "RESEARCH_GET_SUCCESS";
export const RESEARCH_GET_FAIL = "RESEARCH_GET_FAIL"