export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAIL = "USER_DATA_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_TOKEN_PROCESS_REQUEST = "USER_TOKEN_PROCESS_REQUEST";
export const USER_TOKEN_PROCESS_SUCCESS = "USER_TOKEN_PROCESS_SUCCESS";
export const USER_TOKEN_PROCESS_FAIL = "USER_TOKEN_PROCESS_SUCCESS";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";